[package]
name = "spectra_cli"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "spectra"
path = "src/main.rs"

[dependencies]
spectra_core = { path = "../core" }
clap = { version = "4", features = ["derive"] }
colored = "2"
serde_json = "1"
rpassword = "7"
dirs = "5"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
